management:
  health:
    rabbit:
      enabled: false
logging:
  level:
    io:
      pivotal: DEBUG
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
        cloud: WARN

# disable the hystrix streaming on rabbit locally
hystrix:
  stream:
    queue:
      enabled: false

#uaa oauth2 settings
targets:
  uaa: http://localhost:8080/uaa

uaa:
  identity-zone-id: uaa


spring:
  security:
    oauth2:
      client:
        registration:
          pivotalbank:
            clientId: pivotalbank
            clientSecret: secret
#security:
#  oauth2:
#    client:
#      accessTokenUri: ${targets.uaa}/oauth/token
#      userAuthorizationUri: ${targets.uaa}/oauth/authorize
#      clientId: pivotalbank
#      clientSecret: secret
#      scope: openid,bank.admin,trade.buy,trade.sell,portfolio.read,account.open,pivotal.bank
#    resource:
 #     jwk:
 #       key-set-uri: ${targets.uaa}/token_keys

