management:
  health:
    rabbit:
      enabled: false
logging:
  level:
    io:
      pivotal: DEBUG
    com:
      netflix: INFO
    org:
      springframework:
        web: INFO
        cloud: WARN

# disable the hystrix streaming on rabbit locally
hystrix:
  stream:
    queue:
      enabled: false

#uaa oauth2 settings
targets:
  uaa: http://localhost:8090/uaa

uaa:
  identity-zone-id:


spring:
  security:
    oauth2:
      client:
        registration:
          pivotalbank:
            clientId: pivotalbank
            clientSecret: secret

  #datasource:
  #  url: jdbc:mysql://localhost:3306/traderdb
  #  username: traderdb
  #  password: traderdb
  #  driver-class-name: "com.mysql.jdbc.Driver"

