management:
  health:
    rabbit:
      enabled: false
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: INFO
     org:
        springframework:
           web: INFO
           cloud: WARN
spring:
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
# disable the hystrix streaming on rabbit locally
hystrix:
  stream:
    queue:
      enabled: false

#uaa oauth2 settings
targets:
  uaa: http://localhost:8080/uaa

security:
  oauth2:
    client:
      accessTokenUri: ${targets.uaa}/oauth/token
      userAuthorizationUri: ${targets.uaa}/oauth/authorize
      clientId: pivotalbank
      clientSecret: secret
      scope: openid,bank.admin,trade.buy,trade.sell,portfolio.read,account.open,pivotal.bank
    resource:
      jwk:
         key-set-uri: ${targets.uaa}/token_keys
