spring:
  security:
    oauth2:
      client:
        registration:
          pivotalbank:
            clientId: ${vcap.services.uaa-admin.credentials.client-id}
            clientSecret: ${vcap.services.uaa-admin.credentials.client-secret}

logging:
  level:
    org.springframework.security: TRACE

